### ISSUE TITLE
Blocking tile's subdivision after adding a raster layer 

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#567] opened 2017-11-03 13:49 UTC
## Context
In globe example, if we add raster layer after initialization, some tiles stop to subdivide.

## Steps to Reproduce (for bugs)

1. load globe example
2. in console call
```js
globeView.controls.setCameraTargetGeoPosition({ longitude:  6.5, latitude:  46, range: 333000});
```
3. in console call
```js
globeView.addLayer({
    type: 'color',
    url: 'https://raw.githubusercontent.com/iTowns/iTowns2-sample-data/master/croquis.kml',
    protocol: 'rasterizer',
    id: 'Kml',
    name: 'kml',
})
```
4. in console call (he noted that this step should not be necessary)
```js
globeView.controls.setCameraTargetGeoPosition({ longitude:  6.5, latitude:  46, range: 330000});
```

## Possible Cause/Fix/Solution
the bug appears in commit e3db2308f3cca7f6eaa17f68779d48909d92339c

this [line](https://github.com/iTowns/itowns/commit/e3db2308f3cca7f6eaa17f68779d48909d92339c#diff-ad71c3a479d08240c3053171dd65d576R155) seems to be the origin of the bug

`layer.noTextureParentOutsideLimit` and `layerUpdateState` can cause the problem

**Comment by peppsac** [comment] 2017-11-06 10:39
I cannot reproduce based on your description.
`some tiles stop to subdivide` : which ones? under the loaded `kml` file?
Can you add a screenshot?
(or even better: add a failing unit test to illustrate your bug)

**Comment by gchoqueux** [comment] 2017-11-06 11:19
Indeed, I didn't notice that it must be located at a certain level of zoom.
I change main text issue

**Comment by peppsac** [comment] 2017-11-06 19:33
I believe the underlying issue is the use (and misuse) of `layer.ready`:
- `tileInsideLayer` should never depend on `layer.ready`: it could return `undefined` when it cannot determine if a tile is covered by a layer (`Raster_Provider.js` should be fixed)
- layers where `layer.ready` isn't `true` shouldn't be used (`SubdivisionControl.js`, `LayeredMaterialNodeProcessing.js`, and all `*Processing.js` should be fixed. Or `MainLoop.prototype._update` couldn't update non-ready layers).

**Closed as completed** 2017-11-15 17:00 UTC
Labels: bug :bug:
