### ISSUE TITLE
Cubic planar example produces visual artifacts

### ISSUE THREAD

**Issue by fnicollet** [iTowns/itowns#668] opened 2018-02-26 11:29 UTC
Hello,

Trying out the "Cubic planar" example on my laptop:
http://www.itowns-project.org/itowns/examples/cubic_planar.html
When you move the camera around, it generates some artifacts. Some faces become orthogonal to the plane, making them stand out:
![image](https://user-images.githubusercontent.com/1240481/36668082-6e68d4a0-1af0-11e8-8fb5-18081f4ccc09.png)
Also, some tiles never seem to load (wrong LOD or something):
![image](https://user-images.githubusercontent.com/1240481/36668143-ab364804-1af0-11e8-97bb-4585887e0cc1.png)

There is no error in the console
Fabien

**Comment by peppsac** [comment] 2018-02-26 11:43
Thanks for reporting.

This was probably broken by #586 (just tested: it worked before this PR) - so this issue could be considered a duplicate of #642

**Closed as completed** 2018-02-27 10:59 UTC

**Comment by fnicollet** [comment] 2018-02-27 11:03
Is there a delay (travis build)? Because the planar example is still broken

**Comment by fnicollet** [comment] 2018-02-27 11:05
all good 👍
