### ISSUE TITLE
White screen when zooming

### ISSUE THREAD

**Issue by vcoindet** [iTowns/itowns#411] opened 2017-07-24 14:46 UTC
When the globe is ready and you zoom with the scroll wheel, everything suddenly disappears when your close to level 13 (like we were under the globe) and all we can see is a white screen.
The same thing happens when using the `globeView.controls.setZoom()` for levels higher than 9. (same bahavior for `setScale()`, `setRange()` and `setOrbitalPosition()`, which is logical).

It seems that this bug appeared in the following commit https://github.com/iTowns/itowns/commit/6c7d9b6b54c1a06116f5b0962511224385591bc3

**Comment by peppsac** [comment] 2017-07-24 21:03
Nope, it was broken before (I just tried  ea65fc0).

To test you can either do this after the initial loading of `index.html`:
- `globeView.controls.getRange()` should return `25.000.000` - in buggy versions it returns more than 25M
- or `globeView.controls.setRange(1000)` that will display a white screen. But if you then do `globeView.controls.setRange(10000)`, wait for a bit until tiles are loaded and then do `globeView.controls.setRange(1000)` it'll work

The problem is probably in `GlobeView.prototype.getPickingPositionFromDepth` or `GlobeControl`'s `updateCameraTargetOnGlobe` (or both).

**Comment by vcoindet** [comment] 2017-07-25 06:38
Hum... My bad sorry ! ;)

You're effectively right, I guess it is getting worse with the commit I mentionned...
In commit https://github.com/iTowns/itowns/commit/6c7d9b6b54c1a06116f5b0962511224385591bc3 : starts to bug around zoom levels 10 - 13
In commit https://github.com/iTowns/itowns/commit/ea65fc03d0a75896f1508793e3b0707d30efe5d3 : starts to bug around zoom levels 15 - 18

**Comment by peppsac** [comment] 2017-07-25 07:16
Indeed 6c7d9b6 introduces a bug in `unpack1K` function.

With the fix from #412, we're back at the same error level than before - that *might* be caused by precision issues...

**Comment by vcoindet** [comment] 2017-07-25 07:57
> that might be caused by precision issues...

After several tests I arrived to the same conclusion, but we have this kind of problems since a long time ago now... Every time the camera is far from the globe, the altitude accuracy is not that good

**Comment by peppsac** [comment] 2017-09-13 12:52
@gchoqueux why did you close this issue? (you stated in #472 that it **didn't** resolve this issue)

**Comment by gchoqueux** [comment] 2017-09-13 13:02
it's automatic closing with in the  #472 description (with the `resolve` key)

**Closed as completed** 2017-10-23 11:40 UTC
Labels: bug :bug:
