### ISSUE TITLE
Bug with addLayer causing all tiles to refresh

### ISSUE THREAD

**Issue by vocalyang** [iTowns/itowns#2190] opened 2023-09-14 02:41 UTC
I also have this issue with colorlayer adding filesource causing all tiles to refresh.
![123604357-0eccd480-d7fb-11eb-9ffd-33513ddbf74f](https://github.com/iTowns/itowns/assets/25248447/099cf192-5734-4cfa-8007-18fdadc44101)

**Comment by mgermerie** [comment] 2023-09-15 15:13
Hi ! Thanks for your feedback and update on issue #1082. As your issue is a duplicate of #1082, I will close it and we will use #1082 to discuss its fix.

**Closed as completed by mgermerie** 2023-09-15 15:13 UTC
