### ISSUE TITLE
Partial rendering on mobile browsers (no globe, no WMTS tiles, bad controls)

### ISSUE THREAD

**Issue by fnicollet** [iTowns/itowns#645] opened 2018-02-07 11:55 UTC
Hello,

We are looking at different 3D rendering engines, as we want to integrate 3D in our GIS (2D) software.

iTowns works pretty well on Desktop (the WMTS tiles are rather slow but that might be an IGN problem, or maybe the wrong tiles are loaded first depending on the field of view, I am not sure) but we also tried iTowns on a number of mobile devices (android phones, android tablets, ipad mini)

On those platforms, iTowns doesn't work well (or at all). The globe is not displayed as the WMTS tiles seem to never appear. 
Also, the controls are mostly not working on mobile (you can kind of move, zoom in or out, but you can't rotate). Here is a screenshot of the GPX official example on mobile:
![screenshot_20180207-124410](https://user-images.githubusercontent.com/1240481/35915075-e0595462-0c05-11e8-8397-c0e3e6a8e47a.png)
The other examples don't work either, so it is quite easy to reproduce.

iTowns is based on WebGL, which has sparse support on mobile, but other rendering engines work, not sure if they use a fallback or feature detection but they do work.

Our GIS (2D) software is working on mobile and we would need the 3D to work as where on mobile.

It looks like iTowns was not made to be working on mobile. Is it something that is planned at some point or is it out of the focus of the project?

Thanks for your help,
Fabien

**Comment by vpicavet** [comment] 2018-02-07 16:01
Hi,

I would say that iTowns is not specifically developed currently to be used on mobile phones. The problem is primarily with testing. Depending on your device, you may have very different outcome.

They are probably multiple causes for that, from hardware limitations to browser versions and JS support, to real itowns bugs.

That said, we would like to have it work on mobile. Not a strong priority right now, but contributions and bugfixes are welcome.

New controls for mobile should probably be written to be adapted for mobile and tablets.

I guess people at IGN like @nosy-b, @gchoqueux or @gcebelieu  will have an opinion, as geoportail.fr is now using itowns for 3D.

**Comment by fnicollet** [comment] 2018-02-07 22:26
Thanks for the detailed answer, i am also interested to know if the
geoportail team could have something handy to fix that (seems that 3d is
just disabled on mobile)

Fabien

Le 7 févr. 2018 17:01, "Vincent Picavet" <notifications@github.com> a
écrit :

**Comment by autra** [comment] 2018-02-08 08:36
@fnicollet I know that pointcloud examples works on some android devices. To elaborate on what @vpicavet said, I'd say our goal is to support most - if not all - devices that three.js supports.

So what you can do is check if the combination of your hardware + your OS version (because of graphic drivers) + your browser (and its version) is supported by three.js. Some hints will be found [here](https://caniuse.com/#feat=webgl) and also [here](http://webglreport.com/?v=1), but I'm afraid that only testing on [three.js examples](https://threejs.org/examples/) will give you the answer for sure.

If three.js does not support your device, I'm afraid it's game over (but if it's reasonably recent, I'll be surprised if that's the case).

If it does though, then we might be able to do something about it. Please then open an issue for each individual issue you have, following the issue template, *especially* the "Your environment" section (browser, os, device with precise versions and model id). Please post there any error you have in console. Please also post a screenshot of the reports [here](http://webglreport.com/?v=1) here: in your case this holds very important informations.

> i am also interested to know if the geoportail team could have something handy to fix that 

While the geoportail and itowns works in close cooperation, they are 2 different teams. Please go to their github or their contact page for any enquiries you may have (but they'll need a support in itowns as well to activate it on their side).

I'm closing this for now, as I believe your questions has been answered. We'll look at individual issues you may open. We'll still receive the mails about this issue, so don't hesitate to ask further questions here.

**Closed as completed by autra** 2018-02-08 08:36 UTC

**Comment by elias75015** [comment] 2018-02-08 13:56
Hi,

for the moment, the Geoportail website uses iTowns as it is. 

>  i am also interested to know if the geoportail team could have something handy to fix that (seems that 3d is just disabled on mobile)

Indeed, we do not encourage the use of the 3D on mobile devices by disabling it. The availability of the 3D on the Geoportail depends on 2 parameters : the size of the screen, and the version of the browser.

It is planned to implement a safer/cleaner mechanism which will check if webGL is handled by the user device.

> the WMTS tiles are rather slow but that might be an IGN problem, or maybe the wrong tiles are loaded first depending on the field of view, I am not sure

In principle, there is no problem with our WMTS. Please, if you encounter any problem with the Geoportail tiles, do not hesitate to open a topic on our [geoportail API user forum](https://www.developpez.net/forums/f1255/applications/sig-systeme-d-information-geographique/ign-api-geoportail/).

**Comment by nosy-b** [comment] 2018-02-08 16:26
-> #649
