### ISSUE TITLE
Sources with multiple sub-domains are not working

### ISSUE THREAD

**Issue by zarov** [iTowns/itowns#1483] opened 2020-09-28 06:57 UTC
## Context

Sub-domains URL was added last year (#1189), to allow better load balancing on servers. While tests were added, we didn't test it with a real use case. You can try it with the following source:

```js
const tmsSource = new itowns.TMSSource({
    url: 'https://${u:a|b|c|d}.data.osmbuildings.org/0.2/anonymous/tile/15/${x}/${y}.json',
    tileMatrixSet: 'PM',
    isInverted: true,
    projection: 'EPSG:4326',
    format: 'application/json',
});
```

## Expected Behavior

This should work.

## Actual Behavior

It doesn't. Instead, it stops [here](https://github.com/iTowns/itowns/blob/master/src/Core/Scheduler/Scheduler.js#L156), and throws this error: `Uncaught TypeError: Failed to construct 'URL': Invalid URL`.

## Possible Cause/Fix/Solution

Change the way the host is read, by adding either a queue by subdomain(`a.server.geo`, `b.server.geo` and `c.server.geo` for `${u:a|b|c}.server.geo`), or a host minus the subdomain, as a general queue (`server.geo` for `${u:a|b|c}.server.geo`)

**Comment by jailln** [comment] 2022-10-14 09:44
Duplicate of #1883. It has been fixed in #1885.

**Closed as completed by jailln** 2022-10-14 09:44 UTC
Labels: bug :bug:
