### ISSUE TITLE
Some debug tools don't work in planar view

### ISSUE THREAD

**Issue by jailln** [iTowns/itowns#935] opened 2018-11-28 13:23 UTC
Debug tools 'Debug camera' and 'debug event' don't work in planar view.

## Your Environment
* Version used: Current master, SHA1 810a7566b3e4337577bf3d137113d81d7e0576d7
* Browser Name and version: Firefox 62.0.3
* Operating System and version (desktop or mobile): Ubuntu 18.04.1 LTS

## Steps to Reproduce (for bugs)
1. Open [planar example](https://github.com/iTowns/itowns/blob/master/examples/planar.html) in your browser
2. Expand 'Debug Tools' in the menu
3. Checking one of the two following checkbox generate an error:
   * debug Camera 
   * Debug event

## Expected Behavior

The expected behavior can be seen by reproducing the above steps in the [globe WFS extruded example](https://github.com/iTowns/itowns/blob/master/examples/globe_wfs_extruded.html)

## Actual Behavior

Nothing happens when checking these checkboxes and the following errors are generated:
  * 'debug Camera' : 

```
Error: The extent crs is not a Geographic Coordinates (EPSG:4326) itowns.js line 6652 > eval:195:15
extentToOBB
OBB.js:179
renderCameraDebug
Debug.js:165
View.prototype.execFrameRequesters
View.js:644
MainLoop.prototype._renderView
MainLoop.js:308
MainLoop.prototype._step
MainLoop.js:286
MainLoop.prototype.scheduleViewUpdate/<
MainLoop.js:52
```

  * 'Debug event':

`TypeError: controls is undefined[Learn More] debug.js line 4674 > eval:105:13 `

**Comment by gchoqueux** [comment] 2018-11-28 13:41
Thank you for reporting this issue.
Indeed, the debug menu don't fully support the planar mode.
We will fix this bug.

**Comment by gchoqueux** [comment] 2020-01-15 14:41
Debug Camera is fixed in planar mode

**Comment by gchoqueux** [comment] 2021-05-03 08:21
The issue is almost fixed
The coordinates debug event is updated on drag terrain and is screen center. 
@mgermerie could update on mouse move and return the coordinates under mouse?

**Closed as completed** 2021-05-27 08:38 UTC
Labels: bug :bug:
