### ISSUE TITLE
OBB constructor should not have lookat and translate as input params?

### ISSUE THREAD

**Issue by qdnguyen** [iTowns/itowns#549] opened 2017-10-25 13:12 UTC
I want to modify OBB function in TileMesh.js for geoid example so that zFactor does not accumulate on Min Max of OBB. Some thing like:

TileMesh.prototype.OBB = function OBB() {
    var zFactor = this.material.uniforms.zFactor.value;
    var OBB = this.geometry.OBB.clone();
          OBB.box3D.min.z *= zFactor;
          OBB.box3D.max.z *= zFactor;
    return OBB; 
};

To do it, i need a clone function in OBB.js, i tried two solutions 

solution 1:
OBB.prototype.clone = function clone() {
    return new OBB(this.box3D.min.clone(),
                   this.box3D.max.clone(),
                   undefined,
                   undefined);
}; 

solution 2:
OBB.prototype.clone = function clone() {
    return new OBB(this.box3D.min.clone(),
                   this.box3D.max.clone(),
                   this.lookAt,
                   this.translate);
}; 

Both does not work, i think it's because of the need of lookAt and translate params in OBB function of TileMesh. But it's not logic for me that lookAt and translate are input params of OBB contructor. 

Any idea to help me out?

**Comment by autra** [comment] 2017-10-25 13:39
@qdnguyen so in my opinion, questions and call for helps should go into the mailing list. Let's keep issues for actual itowns bug, thanks!

**Comment by qdnguyen** [comment] 2017-10-25 13:42
@autra it 's not only for help, it's also an issue!

**Comment by autra** [comment] 2017-10-25 13:43
@qdnguyen is this an actual reproducible bug on master? Then please follow the issue template and add *at least* steps to reproduce and actual and expected behaviour. Because nothing here allows me to reproduce. Thanks!

**Comment by qdnguyen** [comment] 2017-10-25 13:51
@autra : an issue is not only for bug, right? here the problem is that the code  (i means OBB.js) we generated can not be reused in my case, so i think it's an issue!

**Comment by peppsac** [comment] 2017-11-06 10:48
@qdnguyen it seems that you solved your issue in your PR so I'm closing this issue.

**Closed as completed by peppsac** 2017-11-06 10:48 UTC
Labels: enhancement :rocket:
